---
- name: Configurar Servidor Web (IIS) no Windows
  hosts: all
  gather_facts: no
  tasks:
    - name: Instalar o Web-Server (IIS)
      win_feature:
        name: Web-Server
        state: present
        include_management_tools: yes
      register: iis_install

    - name: Reiniciar o servidor se for necessario apos a instalacao
      win_reboot:
      when: iis_install.reboot_required